import "./globals.css";
import type { Metadata } from "next";
import { Inter } from 'next/font/google'
 
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})
 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} flex flex-col items-center`}
      >
        <header className="w-full max-w-screen-xl py-1">
          <div className="w-full border px-4 py-3 font-semibold rounded-lg">Classroom</div>
        </header>
        <div className="flex">
        <aside className="w-32">
          asd
        </aside>
        {children}
        </div>
      </body>
    </html>
  );
}
